export const ACAO = {
  VISUALIZAR: 'Visualizar',
  INCLUIR: 'Incluir',
  EDITAR: 'Editar',
  EXCLUIR: 'Excluir',
  BAIXAR: 'Baixar',
  ESTORNAR: 'Estornar',
  EXPORTAR: 'Exportar',
} as const;

export const formRouteMap: Record<string, string> = {
  'Dashboard': '/dashboard',
  'Contas a Receber': '/contas-receber',
  'Contas a Pagar': '/contas-pagar',
  'Clientes': '/clientes',
  'Fornecedores': '/fornecedores',
  'Categorias': '/categorias',
  'Servicos': '/servicos',
  'Formularios': '/formularios',
  'Usuario x Formulario': '/usuario-formularios',
  'Usuarios': '/usuarios',
  'Horas Trabalhadas': '/horas-trabalhadas',
  'Horas Excedidas': '/excedidas',
  'Abatimentos': '/abatimentos',
  'Relatorio Financeiro': '/relatorios/financeiro',
  'Relatorio Clientes': '/relatorios/cadastros/clientes',
  'Relatorio Fornecedores': '/relatorios/cadastros/fornecedores',
  'Relatorio Categorias': '/relatorios/cadastros/categorias',
  'Relatorio Usuarios': '/relatorios/cadastros/usuarios',
  'Relatorio Formularios': '/relatorios/cadastros/formularios',
  'Empresas': '/empresas',
  'Insumos': '/insumos',
  'Marcas': '/marcas',
  'Compras Insumo': '/compras-insumo',
  'Produtos Fabricados': '/produtos-fabricados',
  'Custos Adicionais': '/custos-adicionais',
  'Fabricacoes': '/fabricacoes',
  'Vendas Produto': '/vendas-produto',
  'Receitas Ingredientes': '/receitas-ingredientes',
  'Custos Fab.': '/fabricacao-custos-adicionais',
  'Estoque Insumo': '/estoque-insumo',
  'Estoque Produto Fabricado': '/estoque-produto',
  'Modulos': '/modulos',
  'Modulo x Formulario': '/modulo-formularios',
  'Empresa x Modulo': '/empresa-modulos',
  'Configuracoes': '/settings',
  'Permissoes': '/permissoes-formulario',
  'Relatorio Insumos': '/relatorios/producao/insumos',
  'Relatorio Produtos Fabricados': '/relatorios/producao/produtos-fabricados',
  'Relatorio Fabricacoes': '/relatorios/producao/fabricacoes',
  'Relatorio Vendas Produto': '/relatorios/producao/vendas-produto',
  'Lancamentos Automaticos': '/lancamento-automatico-config',
  'Perdas Insumo': '/perdas-insumo',
  'Perdas Produto': '/perdas-produto',
  'Uso Consumo': '/uso-consumo',
};

export const routeFormMap: Record<string, string> = Object.fromEntries(
  Object.entries(formRouteMap).map(([form, route]) => [route, form])
);
