android {
    signingConfigs {
        release {
            storeFile file("release.keystore")
            storePassword "gestor123"
            keyAlias "producao"
            keyPassword "gestor123"
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}
